first commit
jks7878/Todo pull request #1
Opened 2023-02-14 13:09 UTC by jks7878

코드 리뷰 부탁드립니다

2023-02-14 13:14 UTC, kimjooyoon commented on .vscode/launch.json
> +}
```suggestion
}

```

깃허브에서 코드 마지막 줄에는 공백 줄을 추가하는게 좋습니다.

2023-02-14 13:15 UTC, kimjooyoon commented on src/api/user.js
> +module.exports = router;
```suggestion
module.exports = router;

```

2023-02-14 13:16 UTC, kimjooyoon commented on src/config/winston.js
> +module.exports = logger;
```suggestion
module.exports = logger;

```

2023-02-14 13:16 UTC, kimjooyoon commented on src/db/db.js
> +module.exports = new DB;
```suggestion
module.exports = new DB;

```

2023-02-14 13:17 UTC, kimjooyoon requested changes
확인했습니다.

제안했던 코드 스타일 만 수정하시면 좋을 것 같아요.

2023-02-15 01:37 UTC, jks7878 commented
> 확인했습니다.
> 
> 제안했던 코드 스타일 만 수정하시면 좋을 것 같아요.

오 이런 거는 전혀 몰랐네요 감사합니다 바로 적용할게요!

2023-02-15 01:38 UTC, merged